from local_parser.extract_trial_data import store_ids
from local_parser.build_bert_ready_dataset import parse_topics, final_process_df

from local_parser.extract_trial_data import concatenate_returned_queries